[module]
name = "fmt"

[headers]
include_dirs = [
    "samples/fmt/include"
]
library_headers = [
    "fmt/args.h",
    "fmt/chrono.h",
    "fmt/color.h",
    "fmt/compile.h",
    "fmt/format.h",
    { path = "fmt/os.h", if_defined = "FMT_OS" },
    "fmt/ostream.h",
    "fmt/printf.h",
    "fmt/ranges.h",
    "fmt/std.h",
    "fmt/xchar.h"
]

[macros]
expand_from_definition = [
    "FMT_BEGIN_NAMESPACE",
    "FMT_END_NAMESPACE"
]
explicit_macros = [
    "FMT_API",
    "FMT_NORETURN=[[noreturn]]",
    "FMT_NODISCARD=[[noreturn]]",
    "FMT_NO_UNIQUE_ADDRESS=[[no_unique_address]]",
    "FMT_CONSTEXPR=constexpr",
    "FMT_CONSTEVAL=consteval",
    "FMT_CONSTEXPR20=constexpr",
    "FMT_ALWAYS_INLINE=inline"
]